apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: kube-state-metrics
        targetRevision: 5.0.1
        helm:
          valueFiles:
            - $values/kube-state-metrics/values.yaml
      - repoURL: 'https://github.com/walasee/grafana-iac'
        targetRevision: master #branch name 
        ref: values            
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus-node-exporter
        targetRevision: 4.14.0
        helm:
          valueFiles:
            - $values/node_exporter/values.yaml
      - repoURL: 'https://github.com/walasee/grafana-iac'
        targetRevision: master #branch name 
        path: grafana-iac
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true